# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'board.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(714, 584)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setWindowOpacity(1.000000000000000)
        Form.setStyleSheet(u"background-color:blue;")
        self.board = QLabel(Form)
        self.board.setObjectName(u"board")
        self.board.setGeometry(QRect(0, 0, 741, 591))
        self.board.setStyleSheet(u"background-color:rgb(82,72,120)")
        self.board.setPixmap(QPixmap(u"img/board.svg"))
        self.tile_13 = QLabel(Form)
        self.tile_13.setObjectName(u"tile_13")
        self.tile_13.setGeometry(QRect(156, 334, 101, 111))
        self.tile_13.setStyleSheet(u"background-color:none;")
        self.tile_13.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_01 = QLabel(Form)
        self.tile_01.setObjectName(u"tile_01")
        self.tile_01.setGeometry(QRect(205, 57, 101, 111))
        self.tile_01.setStyleSheet(u"background-color:none;")
        self.tile_01.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_02 = QLabel(Form)
        self.tile_02.setObjectName(u"tile_02")
        self.tile_02.setGeometry(QRect(310, 58, 101, 111))
        self.tile_02.setStyleSheet(u"background-color:none;")
        self.tile_02.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_03 = QLabel(Form)
        self.tile_03.setObjectName(u"tile_03")
        self.tile_03.setGeometry(QRect(416, 58, 101, 111))
        self.tile_03.setStyleSheet(u"background-color:none;")
        self.tile_03.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_04 = QLabel(Form)
        self.tile_04.setObjectName(u"tile_04")
        self.tile_04.setGeometry(QRect(154, 151, 101, 111))
        self.tile_04.setStyleSheet(u"background-color:none;")
        self.tile_04.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_06 = QLabel(Form)
        self.tile_06.setObjectName(u"tile_06")
        self.tile_06.setGeometry(QRect(363, 150, 101, 111))
        self.tile_06.setStyleSheet(u"background-color:none;")
        self.tile_06.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_05 = QLabel(Form)
        self.tile_05.setObjectName(u"tile_05")
        self.tile_05.setGeometry(QRect(259, 150, 101, 111))
        self.tile_05.setStyleSheet(u"background-color:none;")
        self.tile_05.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_07 = QLabel(Form)
        self.tile_07.setObjectName(u"tile_07")
        self.tile_07.setGeometry(QRect(468, 150, 101, 111))
        self.tile_07.setStyleSheet(u"background-color:none;")
        self.tile_07.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_09 = QLabel(Form)
        self.tile_09.setObjectName(u"tile_09")
        self.tile_09.setGeometry(QRect(207, 242, 101, 111))
        self.tile_09.setStyleSheet(u"background-color:none;")
        self.tile_09.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_11 = QLabel(Form)
        self.tile_11.setObjectName(u"tile_11")
        self.tile_11.setGeometry(QRect(416, 240, 101, 111))
        self.tile_11.setStyleSheet(u"background-color:none;")
        self.tile_11.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_08 = QLabel(Form)
        self.tile_08.setObjectName(u"tile_08")
        self.tile_08.setGeometry(QRect(103, 241, 101, 111))
        self.tile_08.setStyleSheet(u"background-color:none;")
        self.tile_08.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_10 = QLabel(Form)
        self.tile_10.setObjectName(u"tile_10")
        self.tile_10.setGeometry(QRect(311, 240, 101, 111))
        self.tile_10.setStyleSheet(u"background-color:none;")
        self.tile_10.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_12 = QLabel(Form)
        self.tile_12.setObjectName(u"tile_12")
        self.tile_12.setGeometry(QRect(520, 241, 101, 111))
        self.tile_12.setStyleSheet(u"background-color:none;")
        self.tile_12.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_14 = QLabel(Form)
        self.tile_14.setObjectName(u"tile_14")
        self.tile_14.setGeometry(QRect(259, 333, 101, 111))
        self.tile_14.setStyleSheet(u"background-color:none;")
        self.tile_14.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_19 = QLabel(Form)
        self.tile_19.setObjectName(u"tile_19")
        self.tile_19.setGeometry(QRect(417, 424, 100, 111))
        self.tile_19.setStyleSheet(u"background-color:none;")
        self.tile_19.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_15 = QLabel(Form)
        self.tile_15.setObjectName(u"tile_15")
        self.tile_15.setGeometry(QRect(363, 333, 100, 111))
        self.tile_15.setStyleSheet(u"background-color:none;")
        self.tile_15.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_16 = QLabel(Form)
        self.tile_16.setObjectName(u"tile_16")
        self.tile_16.setGeometry(QRect(470, 334, 100, 111))
        self.tile_16.setStyleSheet(u"background-color:none;")
        self.tile_16.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_18 = QLabel(Form)
        self.tile_18.setObjectName(u"tile_18")
        self.tile_18.setGeometry(QRect(313, 423, 100, 111))
        self.tile_18.setStyleSheet(u"background-color:none;")
        self.tile_18.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_17 = QLabel(Form)
        self.tile_17.setObjectName(u"tile_17")
        self.tile_17.setGeometry(QRect(208, 422, 100, 111))
        self.tile_17.setStyleSheet(u"background-color:none;")
        self.tile_17.setPixmap(QPixmap(u"img/tile.svg"))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Travellers", None))
        self.board.setText("")
        self.tile_13.setText("")
        self.tile_01.setText("")
        self.tile_02.setText("")
        self.tile_03.setText("")
        self.tile_04.setText("")
        self.tile_06.setText("")
        self.tile_05.setText("")
        self.tile_07.setText("")
        self.tile_09.setText("")
        self.tile_11.setText("")
        self.tile_08.setText("")
        self.tile_10.setText("")
        self.tile_12.setText("")
        self.tile_14.setText("")
        self.tile_19.setText("")
        self.tile_15.setText("")
        self.tile_16.setText("")
        self.tile_18.setText("")
        self.tile_17.setText("")
    # retranslateUi

