# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'game.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(900, 590)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QSize(900, 590))
        Form.setWindowOpacity(1.000000000000000)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet(u"")
        self.board = QLabel(Form)
        self.board.setObjectName(u"board")
        self.board.setGeometry(QRect(0, 0, 1000, 591))
        self.board.setStyleSheet(u"background-color:rgb(82,72,120);margin-right:auto;")
        self.board.setPixmap(QPixmap(u"img/board.svg"))
        self.tile_13 = QLabel(Form)
        self.tile_13.setObjectName(u"tile_13")
        self.tile_13.setGeometry(QRect(156, 334, 101, 111))
        self.tile_13.setStyleSheet(u"background-color:none;")
        self.tile_13.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_01 = QLabel(Form)
        self.tile_01.setObjectName(u"tile_01")
        self.tile_01.setGeometry(QRect(205, 57, 101, 111))
        self.tile_01.setStyleSheet(u"background-color:none;")
        self.tile_01.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_02 = QLabel(Form)
        self.tile_02.setObjectName(u"tile_02")
        self.tile_02.setGeometry(QRect(310, 58, 101, 111))
        self.tile_02.setStyleSheet(u"background-color:none;")
        self.tile_02.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_03 = QLabel(Form)
        self.tile_03.setObjectName(u"tile_03")
        self.tile_03.setGeometry(QRect(416, 58, 101, 111))
        self.tile_03.setStyleSheet(u"background-color:none;")
        self.tile_03.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_04 = QLabel(Form)
        self.tile_04.setObjectName(u"tile_04")
        self.tile_04.setGeometry(QRect(154, 151, 101, 111))
        self.tile_04.setStyleSheet(u"background-color:none;")
        self.tile_04.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_06 = QLabel(Form)
        self.tile_06.setObjectName(u"tile_06")
        self.tile_06.setGeometry(QRect(363, 150, 101, 111))
        self.tile_06.setStyleSheet(u"background-color:none;")
        self.tile_06.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_05 = QLabel(Form)
        self.tile_05.setObjectName(u"tile_05")
        self.tile_05.setGeometry(QRect(259, 150, 101, 111))
        self.tile_05.setStyleSheet(u"background-color:none;")
        self.tile_05.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_07 = QLabel(Form)
        self.tile_07.setObjectName(u"tile_07")
        self.tile_07.setGeometry(QRect(468, 150, 101, 111))
        self.tile_07.setStyleSheet(u"background-color:none;")
        self.tile_07.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_09 = QLabel(Form)
        self.tile_09.setObjectName(u"tile_09")
        self.tile_09.setGeometry(QRect(207, 242, 101, 111))
        self.tile_09.setStyleSheet(u"background-color:none;")
        self.tile_09.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_11 = QLabel(Form)
        self.tile_11.setObjectName(u"tile_11")
        self.tile_11.setGeometry(QRect(416, 240, 101, 111))
        self.tile_11.setStyleSheet(u"background-color:none;")
        self.tile_11.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_08 = QLabel(Form)
        self.tile_08.setObjectName(u"tile_08")
        self.tile_08.setGeometry(QRect(103, 241, 101, 111))
        self.tile_08.setStyleSheet(u"background-color:none;")
        self.tile_08.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_10 = QLabel(Form)
        self.tile_10.setObjectName(u"tile_10")
        self.tile_10.setGeometry(QRect(311, 240, 101, 111))
        self.tile_10.setStyleSheet(u"background-color:none;")
        self.tile_10.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_12 = QLabel(Form)
        self.tile_12.setObjectName(u"tile_12")
        self.tile_12.setGeometry(QRect(520, 241, 101, 111))
        self.tile_12.setStyleSheet(u"background-color:none;")
        self.tile_12.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_14 = QLabel(Form)
        self.tile_14.setObjectName(u"tile_14")
        self.tile_14.setGeometry(QRect(259, 333, 101, 111))
        self.tile_14.setStyleSheet(u"background-color:none;")
        self.tile_14.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_19 = QLabel(Form)
        self.tile_19.setObjectName(u"tile_19")
        self.tile_19.setGeometry(QRect(417, 424, 100, 111))
        self.tile_19.setStyleSheet(u"background-color:none;")
        self.tile_19.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_15 = QLabel(Form)
        self.tile_15.setObjectName(u"tile_15")
        self.tile_15.setGeometry(QRect(363, 333, 100, 111))
        self.tile_15.setStyleSheet(u"background-color:none;")
        self.tile_15.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_16 = QLabel(Form)
        self.tile_16.setObjectName(u"tile_16")
        self.tile_16.setGeometry(QRect(470, 334, 100, 111))
        self.tile_16.setStyleSheet(u"background-color:none;")
        self.tile_16.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_18 = QLabel(Form)
        self.tile_18.setObjectName(u"tile_18")
        self.tile_18.setGeometry(QRect(313, 423, 100, 111))
        self.tile_18.setStyleSheet(u"background-color:none;")
        self.tile_18.setPixmap(QPixmap(u"img/tile.svg"))
        self.tile_17 = QLabel(Form)
        self.tile_17.setObjectName(u"tile_17")
        self.tile_17.setGeometry(QRect(208, 422, 100, 111))
        self.tile_17.setStyleSheet(u"background-color:none;")
        self.tile_17.setPixmap(QPixmap(u"img/tile.svg"))
        self.startGameButton = QPushButton(Form)
        self.startGameButton.setObjectName(u"startGameButton")
        self.startGameButton.setEnabled(True)
        self.startGameButton.setGeometry(QRect(230, 260, 271, 61))
        self.startGameButton.setStyleSheet(u"background-color:rgb(82,72,120);color:white;")
        self.startGameButton.setFlat(False)
        self.edge07 = QLabel(Form)
        self.edge07.setObjectName(u"edge07")
        self.edge07.setGeometry(QRect(200, 87, 6, 51))
        self.edge07.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge08 = QLabel(Form)
        self.edge08.setObjectName(u"edge08")
        self.edge08.setGeometry(QRect(305, 88, 6, 51))
        self.edge08.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge01 = QLabel(Form)
        self.edge01.setObjectName(u"edge01")
        self.edge01.setGeometry(QRect(208, 52, 42, 28))
        self.edge01.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge13 = QLabel(Form)
        self.edge13.setObjectName(u"edge13")
        self.edge13.setGeometry(QRect(262, 144, 42, 28))
        self.edge13.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge12 = QLabel(Form)
        self.edge12.setObjectName(u"edge12")
        self.edge12.setGeometry(QRect(207, 144, 42, 28))
        self.edge12.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge02 = QLabel(Form)
        self.edge02.setObjectName(u"edge02")
        self.edge02.setGeometry(QRect(260, 53, 42, 28))
        self.edge02.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge25 = QLabel(Form)
        self.edge25.setObjectName(u"edge25")
        self.edge25.setGeometry(QRect(154, 235, 42, 28))
        self.edge25.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge42 = QLabel(Form)
        self.edge42.setObjectName(u"edge42")
        self.edge42.setGeometry(QRect(210, 330, 43, 26))
        self.edge42.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge57 = QLabel(Form)
        self.edge57.setObjectName(u"edge57")
        self.edge57.setGeometry(QRect(260, 417, 42, 28))
        self.edge57.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge59 = QLabel(Form)
        self.edge59.setObjectName(u"edge59")
        self.edge59.setGeometry(QRect(368, 420, 42, 28))
        self.edge59.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge46 = QLabel(Form)
        self.edge46.setObjectName(u"edge46")
        self.edge46.setGeometry(QRect(420, 330, 42, 28))
        self.edge46.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge44 = QLabel(Form)
        self.edge44.setObjectName(u"edge44")
        self.edge44.setGeometry(QRect(312, 326, 41, 31))
        self.edge44.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge27 = QLabel(Form)
        self.edge27.setObjectName(u"edge27")
        self.edge27.setGeometry(QRect(260, 236, 42, 28))
        self.edge27.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge14 = QLabel(Form)
        self.edge14.setObjectName(u"edge14")
        self.edge14.setGeometry(QRect(312, 144, 42, 28))
        self.edge14.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge16 = QLabel(Form)
        self.edge16.setObjectName(u"edge16")
        self.edge16.setGeometry(QRect(417, 145, 42, 28))
        self.edge16.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge61 = QLabel(Form)
        self.edge61.setObjectName(u"edge61")
        self.edge61.setGeometry(QRect(470, 418, 42, 28))
        self.edge61.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge48 = QLabel(Form)
        self.edge48.setObjectName(u"edge48")
        self.edge48.setGeometry(QRect(521, 327, 42, 28))
        self.edge48.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge33 = QLabel(Form)
        self.edge33.setObjectName(u"edge33")
        self.edge33.setGeometry(QRect(575, 235, 42, 28))
        self.edge33.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge06 = QLabel(Form)
        self.edge06.setObjectName(u"edge06")
        self.edge06.setGeometry(QRect(470, 53, 42, 28))
        self.edge06.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge04 = QLabel(Form)
        self.edge04.setObjectName(u"edge04")
        self.edge04.setGeometry(QRect(362, 51, 42, 28))
        self.edge04.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge18 = QLabel(Form)
        self.edge18.setObjectName(u"edge18")
        self.edge18.setGeometry(QRect(522, 145, 42, 28))
        self.edge18.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge31 = QLabel(Form)
        self.edge31.setObjectName(u"edge31")
        self.edge31.setGeometry(QRect(470, 236, 42, 28))
        self.edge31.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge29 = QLabel(Form)
        self.edge29.setObjectName(u"edge29")
        self.edge29.setGeometry(QRect(365, 236, 42, 28))
        self.edge29.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge09 = QLabel(Form)
        self.edge09.setObjectName(u"edge09")
        self.edge09.setGeometry(QRect(410, 90, 6, 51))
        self.edge09.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge10 = QLabel(Form)
        self.edge10.setObjectName(u"edge10")
        self.edge10.setGeometry(QRect(515, 90, 6, 51))
        self.edge10.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge39 = QLabel(Form)
        self.edge39.setObjectName(u"edge39")
        self.edge39.setGeometry(QRect(620, 273, 6, 51))
        self.edge39.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge66 = QLabel(Form)
        self.edge66.setObjectName(u"edge66")
        self.edge66.setGeometry(QRect(517, 453, 6, 51))
        self.edge66.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge54 = QLabel(Form)
        self.edge54.setObjectName(u"edge54")
        self.edge54.setGeometry(QRect(569, 365, 6, 51))
        self.edge54.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge65 = QLabel(Form)
        self.edge65.setObjectName(u"edge65")
        self.edge65.setGeometry(QRect(412, 455, 6, 51))
        self.edge65.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge64 = QLabel(Form)
        self.edge64.setObjectName(u"edge64")
        self.edge64.setGeometry(QRect(307, 452, 6, 51))
        self.edge64.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge52 = QLabel(Form)
        self.edge52.setObjectName(u"edge52")
        self.edge52.setGeometry(QRect(358, 360, 6, 51))
        self.edge52.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge51 = QLabel(Form)
        self.edge51.setObjectName(u"edge51")
        self.edge51.setGeometry(QRect(254, 362, 6, 51))
        self.edge51.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge35 = QLabel(Form)
        self.edge35.setObjectName(u"edge35")
        self.edge35.setGeometry(QRect(201, 270, 6, 51))
        self.edge35.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.eddge36 = QLabel(Form)
        self.eddge36.setObjectName(u"eddge36")
        self.eddge36.setGeometry(QRect(306, 270, 6, 51))
        self.eddge36.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge37 = QLabel(Form)
        self.edge37.setObjectName(u"edge37")
        self.edge37.setGeometry(QRect(410, 270, 6, 51))
        self.edge37.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge38 = QLabel(Form)
        self.edge38.setObjectName(u"edge38")
        self.edge38.setGeometry(QRect(515, 270, 6, 51))
        self.edge38.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge22 = QLabel(Form)
        self.edge22.setObjectName(u"edge22")
        self.edge22.setGeometry(QRect(463, 180, 6, 51))
        self.edge22.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge21 = QLabel(Form)
        self.edge21.setObjectName(u"edge21")
        self.edge21.setGeometry(QRect(358, 180, 6, 51))
        self.edge21.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge20 = QLabel(Form)
        self.edge20.setObjectName(u"edge20")
        self.edge20.setGeometry(QRect(253, 180, 6, 51))
        self.edge20.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge53 = QLabel(Form)
        self.edge53.setObjectName(u"edge53")
        self.edge53.setGeometry(QRect(463, 362, 6, 51))
        self.edge53.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge19 = QLabel(Form)
        self.edge19.setObjectName(u"edge19")
        self.edge19.setGeometry(QRect(147, 180, 6, 51))
        self.edge19.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge34 = QLabel(Form)
        self.edge34.setObjectName(u"edge34")
        self.edge34.setGeometry(QRect(96, 270, 6, 51))
        self.edge34.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge50 = QLabel(Form)
        self.edge50.setObjectName(u"edge50")
        self.edge50.setGeometry(QRect(150, 363, 6, 51))
        self.edge50.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge63 = QLabel(Form)
        self.edge63.setObjectName(u"edge63")
        self.edge63.setGeometry(QRect(201, 452, 6, 51))
        self.edge63.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.edge41 = QLabel(Form)
        self.edge41.setObjectName(u"edge41")
        self.edge41.setGeometry(QRect(160, 327, 42, 28))
        self.edge41.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge56 = QLabel(Form)
        self.edge56.setObjectName(u"edge56")
        self.edge56.setGeometry(QRect(210, 420, 42, 28))
        self.edge56.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge68 = QLabel(Form)
        self.edge68.setObjectName(u"edge68")
        self.edge68.setGeometry(QRect(262, 510, 42, 28))
        self.edge68.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge70 = QLabel(Form)
        self.edge70.setObjectName(u"edge70")
        self.edge70.setGeometry(QRect(367, 511, 42, 28))
        self.edge70.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge58 = QLabel(Form)
        self.edge58.setObjectName(u"edge58")
        self.edge58.setGeometry(QRect(312, 420, 42, 28))
        self.edge58.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge43 = QLabel(Form)
        self.edge43.setObjectName(u"edge43")
        self.edge43.setGeometry(QRect(260, 330, 42, 26))
        self.edge43.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge26 = QLabel(Form)
        self.edge26.setObjectName(u"edge26")
        self.edge26.setGeometry(QRect(210, 237, 42, 28))
        self.edge26.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge24 = QLabel(Form)
        self.edge24.setObjectName(u"edge24")
        self.edge24.setGeometry(QRect(104, 237, 42, 28))
        self.edge24.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge47 = QLabel(Form)
        self.edge47.setObjectName(u"edge47")
        self.edge47.setGeometry(QRect(470, 330, 42, 28))
        self.edge47.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge32 = QLabel(Form)
        self.edge32.setObjectName(u"edge32")
        self.edge32.setGeometry(QRect(525, 235, 42, 28))
        self.edge32.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge17 = QLabel(Form)
        self.edge17.setObjectName(u"edge17")
        self.edge17.setGeometry(QRect(470, 145, 42, 28))
        self.edge17.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge15 = QLabel(Form)
        self.edge15.setObjectName(u"edge15")
        self.edge15.setGeometry(QRect(366, 144, 42, 28))
        self.edge15.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge30 = QLabel(Form)
        self.edge30.setObjectName(u"edge30")
        self.edge30.setGeometry(QRect(418, 236, 42, 28))
        self.edge30.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge11 = QLabel(Form)
        self.edge11.setObjectName(u"edge11")
        self.edge11.setGeometry(QRect(154, 147, 42, 28))
        self.edge11.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge60 = QLabel(Form)
        self.edge60.setObjectName(u"edge60")
        self.edge60.setGeometry(QRect(418, 420, 42, 28))
        self.edge60.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge72 = QLabel(Form)
        self.edge72.setObjectName(u"edge72")
        self.edge72.setGeometry(QRect(470, 510, 42, 28))
        self.edge72.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge62 = QLabel(Form)
        self.edge62.setObjectName(u"edge62")
        self.edge62.setGeometry(QRect(524, 422, 42, 28))
        self.edge62.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge49 = QLabel(Form)
        self.edge49.setObjectName(u"edge49")
        self.edge49.setGeometry(QRect(576, 328, 42, 28))
        self.edge49.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge05 = QLabel(Form)
        self.edge05.setObjectName(u"edge05")
        self.edge05.setGeometry(QRect(416, 52, 42, 28))
        self.edge05.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge03 = QLabel(Form)
        self.edge03.setObjectName(u"edge03")
        self.edge03.setGeometry(QRect(313, 53, 42, 28))
        self.edge03.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge28 = QLabel(Form)
        self.edge28.setObjectName(u"edge28")
        self.edge28.setGeometry(QRect(315, 235, 42, 28))
        self.edge28.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge45 = QLabel(Form)
        self.edge45.setObjectName(u"edge45")
        self.edge45.setGeometry(QRect(364, 329, 41, 28))
        self.edge45.setPixmap(QPixmap(u"img/edge_lr.svg"))
        self.edge40 = QLabel(Form)
        self.edge40.setObjectName(u"edge40")
        self.edge40.setGeometry(QRect(102, 329, 42, 28))
        self.edge40.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge67 = QLabel(Form)
        self.edge67.setObjectName(u"edge67")
        self.edge67.setGeometry(QRect(210, 510, 42, 28))
        self.edge67.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge55 = QLabel(Form)
        self.edge55.setObjectName(u"edge55")
        self.edge55.setGeometry(QRect(157, 421, 42, 28))
        self.edge55.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge69 = QLabel(Form)
        self.edge69.setObjectName(u"edge69")
        self.edge69.setGeometry(QRect(315, 510, 42, 28))
        self.edge69.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge71 = QLabel(Form)
        self.edge71.setObjectName(u"edge71")
        self.edge71.setGeometry(QRect(420, 510, 42, 28))
        self.edge71.setPixmap(QPixmap(u"img/edge_rl.svg"))
        self.edge23 = QLabel(Form)
        self.edge23.setObjectName(u"edge23")
        self.edge23.setGeometry(QRect(567, 180, 6, 51))
        self.edge23.setPixmap(QPixmap(u"img/edge_straight.svg"))
        self.board.raise_()
        self.tile_13.raise_()
        self.tile_01.raise_()
        self.tile_02.raise_()
        self.tile_03.raise_()
        self.tile_04.raise_()
        self.tile_06.raise_()
        self.tile_05.raise_()
        self.tile_07.raise_()
        self.tile_09.raise_()
        self.tile_11.raise_()
        self.tile_08.raise_()
        self.tile_10.raise_()
        self.tile_12.raise_()
        self.tile_14.raise_()
        self.tile_19.raise_()
        self.tile_15.raise_()
        self.tile_16.raise_()
        self.tile_18.raise_()
        self.tile_17.raise_()
        self.edge07.raise_()
        self.edge08.raise_()
        self.edge01.raise_()
        self.edge13.raise_()
        self.edge12.raise_()
        self.edge02.raise_()
        self.edge25.raise_()
        self.edge42.raise_()
        self.edge57.raise_()
        self.edge59.raise_()
        self.edge46.raise_()
        self.edge44.raise_()
        self.edge27.raise_()
        self.edge14.raise_()
        self.edge16.raise_()
        self.edge61.raise_()
        self.edge48.raise_()
        self.edge33.raise_()
        self.edge06.raise_()
        self.edge04.raise_()
        self.edge18.raise_()
        self.edge31.raise_()
        self.edge29.raise_()
        self.edge09.raise_()
        self.edge10.raise_()
        self.edge39.raise_()
        self.edge66.raise_()
        self.edge54.raise_()
        self.edge65.raise_()
        self.edge64.raise_()
        self.edge52.raise_()
        self.edge51.raise_()
        self.edge35.raise_()
        self.eddge36.raise_()
        self.edge37.raise_()
        self.edge38.raise_()
        self.edge22.raise_()
        self.edge21.raise_()
        self.edge20.raise_()
        self.edge53.raise_()
        self.edge19.raise_()
        self.edge34.raise_()
        self.edge50.raise_()
        self.edge63.raise_()
        self.edge41.raise_()
        self.edge56.raise_()
        self.edge68.raise_()
        self.edge70.raise_()
        self.edge58.raise_()
        self.edge43.raise_()
        self.edge26.raise_()
        self.edge24.raise_()
        self.edge47.raise_()
        self.edge32.raise_()
        self.edge17.raise_()
        self.edge15.raise_()
        self.edge30.raise_()
        self.edge11.raise_()
        self.edge60.raise_()
        self.edge72.raise_()
        self.edge62.raise_()
        self.edge49.raise_()
        self.edge05.raise_()
        self.edge03.raise_()
        self.edge28.raise_()
        self.edge45.raise_()
        self.edge40.raise_()
        self.edge67.raise_()
        self.edge55.raise_()
        self.edge69.raise_()
        self.edge71.raise_()
        self.edge23.raise_()
        self.startGameButton.raise_()

        self.retranslateUi(Form)

        self.startGameButton.setDefault(False)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Travellers", None))
        self.board.setText("")
        self.tile_13.setText("")
        self.tile_01.setText("")
        self.tile_02.setText("")
        self.tile_03.setText("")
        self.tile_04.setText("")
        self.tile_06.setText("")
        self.tile_05.setText("")
        self.tile_07.setText("")
        self.tile_09.setText("")
        self.tile_11.setText("")
        self.tile_08.setText("")
        self.tile_10.setText("")
        self.tile_12.setText("")
        self.tile_14.setText("")
        self.tile_19.setText("")
        self.tile_15.setText("")
        self.tile_16.setText("")
        self.tile_18.setText("")
        self.tile_17.setText("")
        self.startGameButton.setText(QCoreApplication.translate("Form", u"Start New Game", None))
        self.edge07.setText("")
        self.edge08.setText("")
        self.edge01.setText("")
        self.edge13.setText("")
        self.edge12.setText("")
        self.edge02.setText("")
        self.edge25.setText("")
        self.edge42.setText("")
        self.edge57.setText("")
        self.edge59.setText("")
        self.edge46.setText("")
        self.edge44.setText("")
        self.edge27.setText("")
        self.edge14.setText("")
        self.edge16.setText("")
        self.edge61.setText("")
        self.edge48.setText("")
        self.edge33.setText("")
        self.edge06.setText("")
        self.edge04.setText("")
        self.edge18.setText("")
        self.edge31.setText("")
        self.edge29.setText("")
        self.edge09.setText("")
        self.edge10.setText("")
        self.edge39.setText("")
        self.edge66.setText("")
        self.edge54.setText("")
        self.edge65.setText("")
        self.edge64.setText("")
        self.edge52.setText("")
        self.edge51.setText("")
        self.edge35.setText("")
        self.eddge36.setText("")
        self.edge37.setText("")
        self.edge38.setText("")
        self.edge22.setText("")
        self.edge21.setText("")
        self.edge20.setText("")
        self.edge53.setText("")
        self.edge19.setText("")
        self.edge34.setText("")
        self.edge50.setText("")
        self.edge63.setText("")
        self.edge41.setText("")
        self.edge56.setText("")
        self.edge68.setText("")
        self.edge70.setText("")
        self.edge58.setText("")
        self.edge43.setText("")
        self.edge26.setText("")
        self.edge24.setText("")
        self.edge47.setText("")
        self.edge32.setText("")
        self.edge17.setText("")
        self.edge15.setText("")
        self.edge30.setText("")
        self.edge11.setText("")
        self.edge60.setText("")
        self.edge72.setText("")
        self.edge62.setText("")
        self.edge49.setText("")
        self.edge05.setText("")
        self.edge03.setText("")
        self.edge28.setText("")
        self.edge45.setText("")
        self.edge40.setText("")
        self.edge67.setText("")
        self.edge55.setText("")
        self.edge69.setText("")
        self.edge71.setText("")
        self.edge23.setText("")
    # retranslateUi

